version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker-deps:
        patterns: ["*"]
        update-types: ["patch", "minor", "major"]
