name: Get Postman Collection
description: Get postman collection by name (and fork).
branding:
  icon: arrow-down
  color: orange
inputs:
  postman-key:
    description: Postman API key
    required: true
  collection-name:
    description: Name of the Postman collection
    required: true
  collection-fork:
    description: Name of the Postman fork. If equal to the repository's main branch or null, then the original collection is used.
    required: false
  export-output:
    description: Path to the postman collection export
    required: false
    default: postman.json
outputs:
  collection-uuid:
    description: The UUID of the collection that was exported

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.collection-name }}
    - ${{ inputs.postman-key }}
    - ${{ inputs.export-output }}
    - ${{ inputs.collection-fork }}
